server:
  port:
    8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**

infra:
  discord: https://discord.com/api/webhooks/1244299981607931935/z88NQ05k5mK73SHj_Zx4GsEzuR718tHMezVOIVgYEagTluaGCW0QswGTWwSj1h-82r5r